/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateTweetInput = {
  id?: string | null,
  created_at?: string | null,
  id_str?: string | null,
  text?: string | null,
  source?: string | null,
  truncated?: boolean | null,
  in_reply_to_status_id?: string | null,
  in_reply_to_status_id_str?: string | null,
  in_reply_to_user_id?: string | null,
  in_reply_to_user_id_str?: string | null,
  in_reply_to_screen_name?: string | null,
  userID: string,
  coordinates?: CoordinatesInput | null,
  place?: PlaceInput | null,
  quoted_status_id?: string | null,
  quoted_status_id_str?: string | null,
  is_quote_status?: boolean | null,
  quote_count?: number | null,
  reply_count?: number | null,
  retweet_count?: number | null,
  favorite_count?: number | null,
  entities?: EntityInput | null,
  favorited?: boolean | null,
  retweeted?: boolean | null,
  possibly_sensitive?: boolean | null,
  filter_level?: string | null,
  lang?: string | null,
  last?: boolean | null,
};

export type CoordinatesInput = {
  coordinates?: Array< number | null > | null,
  type?: string | null,
};

export type PlaceInput = {
  id?: string | null,
  url?: string | null,
  place_type?: string | null,
  name?: string | null,
  full_name?: string | null,
  country_code?: string | null,
  country?: string | null,
};

export type EntityInput = {
  hashtags?: Array< HashtagInput | null > | null,
  media?: Array< MediaInput | null > | null,
  urls?: Array< UrlInput | null > | null,
  user_mentions?: Array< UserMentionInput | null > | null,
  symbols?: Array< SymbolInput | null > | null,
  polls?: Array< PollInput | null > | null,
};

export type HashtagInput = {
  indices?: Array< number | null > | null,
  text?: string | null,
};

export type MediaInput = {
  display_url?: string | null,
  expanded_url?: string | null,
  id?: string | null,
  id_str?: Array< string | null > | null,
  indices?: Array< number | null > | null,
  source_user_id?: string | null,
  source_user_id_str?: string | null,
  media_url?: string | null,
  media_url_https?: string | null,
  sizes?: SizesInput | null,
  source_status_id?: string | null,
  source_status_id_str?: string | null,
  type?: string | null,
  url?: string | null,
};

export type SizesInput = {
  thumb?: SizeInput | null,
  small?: SizeInput | null,
  medium?: SizeInput | null,
  large?: SizeInput | null,
};

export type SizeInput = {
  w?: number | null,
  h?: number | null,
  resize?: string | null,
};

export type UrlInput = {
  display_url?: string | null,
  expanded_url?: string | null,
  indices?: Array< number | null > | null,
  url?: string | null,
};

export type UserMentionInput = {
  id?: string | null,
  id_str?: string | null,
  indices?: Array< number | null > | null,
  name?: string | null,
  screen_name?: string | null,
};

export type SymbolInput = {
  indices?: Array< number | null > | null,
  text?: string | null,
};

export type PollInput = {
  options?: Array< OptionInput | null > | null,
  end_datetime?: string | null,
  duration_minutes?: string | null,
};

export type OptionInput = {
  position?: number | null,
  text?: string | null,
};

export type ModelTweetConditionInput = {
  created_at?: ModelStringInput | null,
  id_str?: ModelStringInput | null,
  text?: ModelStringInput | null,
  source?: ModelStringInput | null,
  truncated?: ModelBooleanInput | null,
  in_reply_to_status_id?: ModelStringInput | null,
  in_reply_to_status_id_str?: ModelStringInput | null,
  in_reply_to_user_id?: ModelStringInput | null,
  in_reply_to_user_id_str?: ModelStringInput | null,
  in_reply_to_screen_name?: ModelStringInput | null,
  userID?: ModelIDInput | null,
  quoted_status_id?: ModelStringInput | null,
  quoted_status_id_str?: ModelStringInput | null,
  is_quote_status?: ModelBooleanInput | null,
  quote_count?: ModelIntInput | null,
  reply_count?: ModelIntInput | null,
  retweet_count?: ModelIntInput | null,
  favorite_count?: ModelIntInput | null,
  favorited?: ModelBooleanInput | null,
  retweeted?: ModelBooleanInput | null,
  possibly_sensitive?: ModelBooleanInput | null,
  filter_level?: ModelStringInput | null,
  lang?: ModelStringInput | null,
  last?: ModelBooleanInput | null,
  and?: Array< ModelTweetConditionInput | null > | null,
  or?: Array< ModelTweetConditionInput | null > | null,
  not?: ModelTweetConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type UpdateTweetInput = {
  id: string,
  created_at?: string | null,
  id_str?: string | null,
  text?: string | null,
  source?: string | null,
  truncated?: boolean | null,
  in_reply_to_status_id?: string | null,
  in_reply_to_status_id_str?: string | null,
  in_reply_to_user_id?: string | null,
  in_reply_to_user_id_str?: string | null,
  in_reply_to_screen_name?: string | null,
  userID?: string | null,
  coordinates?: CoordinatesInput | null,
  place?: PlaceInput | null,
  quoted_status_id?: string | null,
  quoted_status_id_str?: string | null,
  is_quote_status?: boolean | null,
  quote_count?: number | null,
  reply_count?: number | null,
  retweet_count?: number | null,
  favorite_count?: number | null,
  entities?: EntityInput | null,
  favorited?: boolean | null,
  retweeted?: boolean | null,
  possibly_sensitive?: boolean | null,
  filter_level?: string | null,
  lang?: string | null,
  last?: boolean | null,
};

export type DeleteTweetInput = {
  id?: string | null,
};

export type CreateUserInput = {
  id?: string | null,
  id_str?: string | null,
  name?: string | null,
  screen_name?: string | null,
  location?: string | null,
  url?: string | null,
  description?: string | null,
  protected?: boolean | null,
  verified?: boolean | null,
  followers_count?: number | null,
  friends_count?: number | null,
  listed_count?: number | null,
  favourites_count?: number | null,
  statuses_count?: number | null,
  created_at?: string | null,
  profile_banner_url?: string | null,
  profile_image_url_https?: string | null,
  default_profile?: boolean | null,
  default_profile_image?: boolean | null,
  withheld_in_countries?: Array< string | null > | null,
  withheld_scope?: string | null,
};

export type ModelUserConditionInput = {
  id_str?: ModelStringInput | null,
  name?: ModelStringInput | null,
  screen_name?: ModelStringInput | null,
  location?: ModelStringInput | null,
  url?: ModelStringInput | null,
  description?: ModelStringInput | null,
  protected?: ModelBooleanInput | null,
  verified?: ModelBooleanInput | null,
  followers_count?: ModelIntInput | null,
  friends_count?: ModelIntInput | null,
  listed_count?: ModelIntInput | null,
  favourites_count?: ModelIntInput | null,
  statuses_count?: ModelIntInput | null,
  created_at?: ModelStringInput | null,
  profile_banner_url?: ModelStringInput | null,
  profile_image_url_https?: ModelStringInput | null,
  default_profile?: ModelBooleanInput | null,
  default_profile_image?: ModelBooleanInput | null,
  withheld_in_countries?: ModelStringInput | null,
  withheld_scope?: ModelStringInput | null,
  and?: Array< ModelUserConditionInput | null > | null,
  or?: Array< ModelUserConditionInput | null > | null,
  not?: ModelUserConditionInput | null,
};

export type UpdateUserInput = {
  id: string,
  id_str?: string | null,
  name?: string | null,
  screen_name?: string | null,
  location?: string | null,
  url?: string | null,
  description?: string | null,
  protected?: boolean | null,
  verified?: boolean | null,
  followers_count?: number | null,
  friends_count?: number | null,
  listed_count?: number | null,
  favourites_count?: number | null,
  statuses_count?: number | null,
  created_at?: string | null,
  profile_banner_url?: string | null,
  profile_image_url_https?: string | null,
  default_profile?: boolean | null,
  default_profile_image?: boolean | null,
  withheld_in_countries?: Array< string | null > | null,
  withheld_scope?: string | null,
};

export type DeleteUserInput = {
  id?: string | null,
};

export type ModelTweetFilterInput = {
  id?: ModelIDInput | null,
  created_at?: ModelStringInput | null,
  id_str?: ModelStringInput | null,
  text?: ModelStringInput | null,
  source?: ModelStringInput | null,
  truncated?: ModelBooleanInput | null,
  in_reply_to_status_id?: ModelStringInput | null,
  in_reply_to_status_id_str?: ModelStringInput | null,
  in_reply_to_user_id?: ModelStringInput | null,
  in_reply_to_user_id_str?: ModelStringInput | null,
  in_reply_to_screen_name?: ModelStringInput | null,
  userID?: ModelIDInput | null,
  quoted_status_id?: ModelStringInput | null,
  quoted_status_id_str?: ModelStringInput | null,
  is_quote_status?: ModelBooleanInput | null,
  quote_count?: ModelIntInput | null,
  reply_count?: ModelIntInput | null,
  retweet_count?: ModelIntInput | null,
  favorite_count?: ModelIntInput | null,
  favorited?: ModelBooleanInput | null,
  retweeted?: ModelBooleanInput | null,
  possibly_sensitive?: ModelBooleanInput | null,
  filter_level?: ModelStringInput | null,
  lang?: ModelStringInput | null,
  last?: ModelBooleanInput | null,
  and?: Array< ModelTweetFilterInput | null > | null,
  or?: Array< ModelTweetFilterInput | null > | null,
  not?: ModelTweetFilterInput | null,
};

export type ModelUserFilterInput = {
  id?: ModelIDInput | null,
  id_str?: ModelStringInput | null,
  name?: ModelStringInput | null,
  screen_name?: ModelStringInput | null,
  location?: ModelStringInput | null,
  url?: ModelStringInput | null,
  description?: ModelStringInput | null,
  protected?: ModelBooleanInput | null,
  verified?: ModelBooleanInput | null,
  followers_count?: ModelIntInput | null,
  friends_count?: ModelIntInput | null,
  listed_count?: ModelIntInput | null,
  favourites_count?: ModelIntInput | null,
  statuses_count?: ModelIntInput | null,
  created_at?: ModelStringInput | null,
  profile_banner_url?: ModelStringInput | null,
  profile_image_url_https?: ModelStringInput | null,
  default_profile?: ModelBooleanInput | null,
  default_profile_image?: ModelBooleanInput | null,
  withheld_in_countries?: ModelStringInput | null,
  withheld_scope?: ModelStringInput | null,
  and?: Array< ModelUserFilterInput | null > | null,
  or?: Array< ModelUserFilterInput | null > | null,
  not?: ModelUserFilterInput | null,
};

export type SearchableTweetFilterInput = {
  id?: SearchableIDFilterInput | null,
  created_at?: SearchableStringFilterInput | null,
  id_str?: SearchableStringFilterInput | null,
  text?: SearchableStringFilterInput | null,
  source?: SearchableStringFilterInput | null,
  truncated?: SearchableBooleanFilterInput | null,
  in_reply_to_status_id?: SearchableStringFilterInput | null,
  in_reply_to_status_id_str?: SearchableStringFilterInput | null,
  in_reply_to_user_id?: SearchableStringFilterInput | null,
  in_reply_to_user_id_str?: SearchableStringFilterInput | null,
  in_reply_to_screen_name?: SearchableStringFilterInput | null,
  userID?: SearchableIDFilterInput | null,
  quoted_status_id?: SearchableStringFilterInput | null,
  quoted_status_id_str?: SearchableStringFilterInput | null,
  is_quote_status?: SearchableBooleanFilterInput | null,
  quote_count?: SearchableIntFilterInput | null,
  reply_count?: SearchableIntFilterInput | null,
  retweet_count?: SearchableIntFilterInput | null,
  favorite_count?: SearchableIntFilterInput | null,
  favorited?: SearchableBooleanFilterInput | null,
  retweeted?: SearchableBooleanFilterInput | null,
  possibly_sensitive?: SearchableBooleanFilterInput | null,
  filter_level?: SearchableStringFilterInput | null,
  lang?: SearchableStringFilterInput | null,
  last?: SearchableBooleanFilterInput | null,
  and?: Array< SearchableTweetFilterInput | null > | null,
  or?: Array< SearchableTweetFilterInput | null > | null,
  not?: SearchableTweetFilterInput | null,
};

export type SearchableIDFilterInput = {
  ne?: string | null,
  gt?: string | null,
  lt?: string | null,
  gte?: string | null,
  lte?: string | null,
  eq?: string | null,
  match?: string | null,
  matchPhrase?: string | null,
  matchPhrasePrefix?: string | null,
  multiMatch?: string | null,
  exists?: boolean | null,
  wildcard?: string | null,
  regexp?: string | null,
  range?: Array< string | null > | null,
};

export type SearchableStringFilterInput = {
  ne?: string | null,
  gt?: string | null,
  lt?: string | null,
  gte?: string | null,
  lte?: string | null,
  eq?: string | null,
  match?: string | null,
  matchPhrase?: string | null,
  matchPhrasePrefix?: string | null,
  multiMatch?: string | null,
  exists?: boolean | null,
  wildcard?: string | null,
  regexp?: string | null,
  range?: Array< string | null > | null,
};

export type SearchableBooleanFilterInput = {
  eq?: boolean | null,
  ne?: boolean | null,
};

export type SearchableIntFilterInput = {
  ne?: number | null,
  gt?: number | null,
  lt?: number | null,
  gte?: number | null,
  lte?: number | null,
  eq?: number | null,
  range?: Array< number | null > | null,
};

export type SearchableTweetSortInput = {
  field?: SearchableTweetSortableFields | null,
  direction?: SearchableSortDirection | null,
};

export enum SearchableTweetSortableFields {
  id = "id",
  created_at = "created_at",
  id_str = "id_str",
  text = "text",
  source = "source",
  truncated = "truncated",
  in_reply_to_status_id = "in_reply_to_status_id",
  in_reply_to_status_id_str = "in_reply_to_status_id_str",
  in_reply_to_user_id = "in_reply_to_user_id",
  in_reply_to_user_id_str = "in_reply_to_user_id_str",
  in_reply_to_screen_name = "in_reply_to_screen_name",
  userID = "userID",
  quoted_status_id = "quoted_status_id",
  quoted_status_id_str = "quoted_status_id_str",
  is_quote_status = "is_quote_status",
  quote_count = "quote_count",
  reply_count = "reply_count",
  retweet_count = "retweet_count",
  favorite_count = "favorite_count",
  favorited = "favorited",
  retweeted = "retweeted",
  possibly_sensitive = "possibly_sensitive",
  filter_level = "filter_level",
  lang = "lang",
  last = "last",
}


export enum SearchableSortDirection {
  asc = "asc",
  desc = "desc",
}


export type CreateTweetMutationVariables = {
  input: CreateTweetInput,
  condition?: ModelTweetConditionInput | null,
};

export type CreateTweetMutation = {
  createTweet:  {
    __typename: "Tweet",
    id: string | null,
    created_at: string | null,
    id_str: string | null,
    text: string | null,
    source: string | null,
    truncated: boolean | null,
    in_reply_to_status_id: string | null,
    in_reply_to_status_id_str: string | null,
    in_reply_to_user_id: string | null,
    in_reply_to_user_id_str: string | null,
    in_reply_to_screen_name: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string | null,
      id_str: string | null,
      name: string | null,
      screen_name: string | null,
      location: string | null,
      url: string | null,
      description: string | null,
      protected: boolean | null,
      verified: boolean | null,
      followers_count: number | null,
      friends_count: number | null,
      listed_count: number | null,
      favourites_count: number | null,
      statuses_count: number | null,
      created_at: string | null,
      profile_banner_url: string | null,
      profile_image_url_https: string | null,
      default_profile: boolean | null,
      default_profile_image: boolean | null,
      withheld_in_countries: Array< string | null > | null,
      withheld_scope: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    coordinates:  {
      __typename: "Coordinates",
      coordinates: Array< number | null > | null,
      type: string | null,
    } | null,
    place:  {
      __typename: "Place",
      id: string | null,
      url: string | null,
      place_type: string | null,
      name: string | null,
      full_name: string | null,
      country_code: string | null,
      country: string | null,
    } | null,
    quoted_status_id: string | null,
    quoted_status_id_str: string | null,
    is_quote_status: boolean | null,
    quote_count: number | null,
    reply_count: number | null,
    retweet_count: number | null,
    favorite_count: number | null,
    entities:  {
      __typename: "Entity",
      hashtags:  Array< {
        __typename: "Hashtag",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      media:  Array< {
        __typename: "Media",
        display_url: string | null,
        expanded_url: string | null,
        id: string | null,
        id_str: Array< string | null > | null,
        indices: Array< number | null > | null,
        source_user_id: string | null,
        source_user_id_str: string | null,
        media_url: string | null,
        media_url_https: string | null,
        source_status_id: string | null,
        source_status_id_str: string | null,
        type: string | null,
        url: string | null,
      } | null > | null,
      urls:  Array< {
        __typename: "Url",
        display_url: string | null,
        expanded_url: string | null,
        indices: Array< number | null > | null,
        url: string | null,
      } | null > | null,
      user_mentions:  Array< {
        __typename: "UserMention",
        id: string | null,
        id_str: string | null,
        indices: Array< number | null > | null,
        name: string | null,
        screen_name: string | null,
      } | null > | null,
      symbols:  Array< {
        __typename: "Symbol",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      polls:  Array< {
        __typename: "Poll",
        options:  Array< {
          __typename: "Option",
          position: number | null,
          text: string | null,
        } | null > | null,
        end_datetime: string | null,
        duration_minutes: string | null,
      } | null > | null,
    } | null,
    favorited: boolean | null,
    retweeted: boolean | null,
    possibly_sensitive: boolean | null,
    filter_level: string | null,
    lang: string | null,
    last: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateTweetMutationVariables = {
  input: UpdateTweetInput,
  condition?: ModelTweetConditionInput | null,
};

export type UpdateTweetMutation = {
  updateTweet:  {
    __typename: "Tweet",
    id: string | null,
    created_at: string | null,
    id_str: string | null,
    text: string | null,
    source: string | null,
    truncated: boolean | null,
    in_reply_to_status_id: string | null,
    in_reply_to_status_id_str: string | null,
    in_reply_to_user_id: string | null,
    in_reply_to_user_id_str: string | null,
    in_reply_to_screen_name: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string | null,
      id_str: string | null,
      name: string | null,
      screen_name: string | null,
      location: string | null,
      url: string | null,
      description: string | null,
      protected: boolean | null,
      verified: boolean | null,
      followers_count: number | null,
      friends_count: number | null,
      listed_count: number | null,
      favourites_count: number | null,
      statuses_count: number | null,
      created_at: string | null,
      profile_banner_url: string | null,
      profile_image_url_https: string | null,
      default_profile: boolean | null,
      default_profile_image: boolean | null,
      withheld_in_countries: Array< string | null > | null,
      withheld_scope: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    coordinates:  {
      __typename: "Coordinates",
      coordinates: Array< number | null > | null,
      type: string | null,
    } | null,
    place:  {
      __typename: "Place",
      id: string | null,
      url: string | null,
      place_type: string | null,
      name: string | null,
      full_name: string | null,
      country_code: string | null,
      country: string | null,
    } | null,
    quoted_status_id: string | null,
    quoted_status_id_str: string | null,
    is_quote_status: boolean | null,
    quote_count: number | null,
    reply_count: number | null,
    retweet_count: number | null,
    favorite_count: number | null,
    entities:  {
      __typename: "Entity",
      hashtags:  Array< {
        __typename: "Hashtag",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      media:  Array< {
        __typename: "Media",
        display_url: string | null,
        expanded_url: string | null,
        id: string | null,
        id_str: Array< string | null > | null,
        indices: Array< number | null > | null,
        source_user_id: string | null,
        source_user_id_str: string | null,
        media_url: string | null,
        media_url_https: string | null,
        source_status_id: string | null,
        source_status_id_str: string | null,
        type: string | null,
        url: string | null,
      } | null > | null,
      urls:  Array< {
        __typename: "Url",
        display_url: string | null,
        expanded_url: string | null,
        indices: Array< number | null > | null,
        url: string | null,
      } | null > | null,
      user_mentions:  Array< {
        __typename: "UserMention",
        id: string | null,
        id_str: string | null,
        indices: Array< number | null > | null,
        name: string | null,
        screen_name: string | null,
      } | null > | null,
      symbols:  Array< {
        __typename: "Symbol",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      polls:  Array< {
        __typename: "Poll",
        options:  Array< {
          __typename: "Option",
          position: number | null,
          text: string | null,
        } | null > | null,
        end_datetime: string | null,
        duration_minutes: string | null,
      } | null > | null,
    } | null,
    favorited: boolean | null,
    retweeted: boolean | null,
    possibly_sensitive: boolean | null,
    filter_level: string | null,
    lang: string | null,
    last: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteTweetMutationVariables = {
  input: DeleteTweetInput,
  condition?: ModelTweetConditionInput | null,
};

export type DeleteTweetMutation = {
  deleteTweet:  {
    __typename: "Tweet",
    id: string | null,
    created_at: string | null,
    id_str: string | null,
    text: string | null,
    source: string | null,
    truncated: boolean | null,
    in_reply_to_status_id: string | null,
    in_reply_to_status_id_str: string | null,
    in_reply_to_user_id: string | null,
    in_reply_to_user_id_str: string | null,
    in_reply_to_screen_name: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string | null,
      id_str: string | null,
      name: string | null,
      screen_name: string | null,
      location: string | null,
      url: string | null,
      description: string | null,
      protected: boolean | null,
      verified: boolean | null,
      followers_count: number | null,
      friends_count: number | null,
      listed_count: number | null,
      favourites_count: number | null,
      statuses_count: number | null,
      created_at: string | null,
      profile_banner_url: string | null,
      profile_image_url_https: string | null,
      default_profile: boolean | null,
      default_profile_image: boolean | null,
      withheld_in_countries: Array< string | null > | null,
      withheld_scope: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    coordinates:  {
      __typename: "Coordinates",
      coordinates: Array< number | null > | null,
      type: string | null,
    } | null,
    place:  {
      __typename: "Place",
      id: string | null,
      url: string | null,
      place_type: string | null,
      name: string | null,
      full_name: string | null,
      country_code: string | null,
      country: string | null,
    } | null,
    quoted_status_id: string | null,
    quoted_status_id_str: string | null,
    is_quote_status: boolean | null,
    quote_count: number | null,
    reply_count: number | null,
    retweet_count: number | null,
    favorite_count: number | null,
    entities:  {
      __typename: "Entity",
      hashtags:  Array< {
        __typename: "Hashtag",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      media:  Array< {
        __typename: "Media",
        display_url: string | null,
        expanded_url: string | null,
        id: string | null,
        id_str: Array< string | null > | null,
        indices: Array< number | null > | null,
        source_user_id: string | null,
        source_user_id_str: string | null,
        media_url: string | null,
        media_url_https: string | null,
        source_status_id: string | null,
        source_status_id_str: string | null,
        type: string | null,
        url: string | null,
      } | null > | null,
      urls:  Array< {
        __typename: "Url",
        display_url: string | null,
        expanded_url: string | null,
        indices: Array< number | null > | null,
        url: string | null,
      } | null > | null,
      user_mentions:  Array< {
        __typename: "UserMention",
        id: string | null,
        id_str: string | null,
        indices: Array< number | null > | null,
        name: string | null,
        screen_name: string | null,
      } | null > | null,
      symbols:  Array< {
        __typename: "Symbol",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      polls:  Array< {
        __typename: "Poll",
        options:  Array< {
          __typename: "Option",
          position: number | null,
          text: string | null,
        } | null > | null,
        end_datetime: string | null,
        duration_minutes: string | null,
      } | null > | null,
    } | null,
    favorited: boolean | null,
    retweeted: boolean | null,
    possibly_sensitive: boolean | null,
    filter_level: string | null,
    lang: string | null,
    last: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateUserMutationVariables = {
  input: CreateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type CreateUserMutation = {
  createUser:  {
    __typename: "User",
    id: string | null,
    id_str: string | null,
    name: string | null,
    screen_name: string | null,
    location: string | null,
    url: string | null,
    description: string | null,
    protected: boolean | null,
    verified: boolean | null,
    followers_count: number | null,
    friends_count: number | null,
    listed_count: number | null,
    favourites_count: number | null,
    statuses_count: number | null,
    created_at: string | null,
    profile_banner_url: string | null,
    profile_image_url_https: string | null,
    default_profile: boolean | null,
    default_profile_image: boolean | null,
    withheld_in_countries: Array< string | null > | null,
    withheld_scope: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateUserMutationVariables = {
  input: UpdateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type UpdateUserMutation = {
  updateUser:  {
    __typename: "User",
    id: string | null,
    id_str: string | null,
    name: string | null,
    screen_name: string | null,
    location: string | null,
    url: string | null,
    description: string | null,
    protected: boolean | null,
    verified: boolean | null,
    followers_count: number | null,
    friends_count: number | null,
    listed_count: number | null,
    favourites_count: number | null,
    statuses_count: number | null,
    created_at: string | null,
    profile_banner_url: string | null,
    profile_image_url_https: string | null,
    default_profile: boolean | null,
    default_profile_image: boolean | null,
    withheld_in_countries: Array< string | null > | null,
    withheld_scope: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteUserMutationVariables = {
  input: DeleteUserInput,
  condition?: ModelUserConditionInput | null,
};

export type DeleteUserMutation = {
  deleteUser:  {
    __typename: "User",
    id: string | null,
    id_str: string | null,
    name: string | null,
    screen_name: string | null,
    location: string | null,
    url: string | null,
    description: string | null,
    protected: boolean | null,
    verified: boolean | null,
    followers_count: number | null,
    friends_count: number | null,
    listed_count: number | null,
    favourites_count: number | null,
    statuses_count: number | null,
    created_at: string | null,
    profile_banner_url: string | null,
    profile_image_url_https: string | null,
    default_profile: boolean | null,
    default_profile_image: boolean | null,
    withheld_in_countries: Array< string | null > | null,
    withheld_scope: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetTweetsQueryVariables = {
  username?: string | null,
};

export type GetTweetsQuery = {
  getTweets:  Array< {
    __typename: "Tweet",
    id: string | null,
    created_at: string | null,
    id_str: string | null,
    text: string | null,
    source: string | null,
    truncated: boolean | null,
    in_reply_to_status_id: string | null,
    in_reply_to_status_id_str: string | null,
    in_reply_to_user_id: string | null,
    in_reply_to_user_id_str: string | null,
    in_reply_to_screen_name: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string | null,
      id_str: string | null,
      name: string | null,
      screen_name: string | null,
      location: string | null,
      url: string | null,
      description: string | null,
      protected: boolean | null,
      verified: boolean | null,
      followers_count: number | null,
      friends_count: number | null,
      listed_count: number | null,
      favourites_count: number | null,
      statuses_count: number | null,
      created_at: string | null,
      profile_banner_url: string | null,
      profile_image_url_https: string | null,
      default_profile: boolean | null,
      default_profile_image: boolean | null,
      withheld_in_countries: Array< string | null > | null,
      withheld_scope: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    coordinates:  {
      __typename: "Coordinates",
      coordinates: Array< number | null > | null,
      type: string | null,
    } | null,
    place:  {
      __typename: "Place",
      id: string | null,
      url: string | null,
      place_type: string | null,
      name: string | null,
      full_name: string | null,
      country_code: string | null,
      country: string | null,
    } | null,
    quoted_status_id: string | null,
    quoted_status_id_str: string | null,
    is_quote_status: boolean | null,
    quote_count: number | null,
    reply_count: number | null,
    retweet_count: number | null,
    favorite_count: number | null,
    entities:  {
      __typename: "Entity",
      hashtags:  Array< {
        __typename: "Hashtag",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      media:  Array< {
        __typename: "Media",
        display_url: string | null,
        expanded_url: string | null,
        id: string | null,
        id_str: Array< string | null > | null,
        indices: Array< number | null > | null,
        source_user_id: string | null,
        source_user_id_str: string | null,
        media_url: string | null,
        media_url_https: string | null,
        source_status_id: string | null,
        source_status_id_str: string | null,
        type: string | null,
        url: string | null,
      } | null > | null,
      urls:  Array< {
        __typename: "Url",
        display_url: string | null,
        expanded_url: string | null,
        indices: Array< number | null > | null,
        url: string | null,
      } | null > | null,
      user_mentions:  Array< {
        __typename: "UserMention",
        id: string | null,
        id_str: string | null,
        indices: Array< number | null > | null,
        name: string | null,
        screen_name: string | null,
      } | null > | null,
      symbols:  Array< {
        __typename: "Symbol",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      polls:  Array< {
        __typename: "Poll",
        options:  Array< {
          __typename: "Option",
          position: number | null,
          text: string | null,
        } | null > | null,
        end_datetime: string | null,
        duration_minutes: string | null,
      } | null > | null,
    } | null,
    favorited: boolean | null,
    retweeted: boolean | null,
    possibly_sensitive: boolean | null,
    filter_level: string | null,
    lang: string | null,
    last: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null > | null,
};

export type GetTweetQueryVariables = {
  id: string,
};

export type GetTweetQuery = {
  getTweet:  {
    __typename: "Tweet",
    id: string | null,
    created_at: string | null,
    id_str: string | null,
    text: string | null,
    source: string | null,
    truncated: boolean | null,
    in_reply_to_status_id: string | null,
    in_reply_to_status_id_str: string | null,
    in_reply_to_user_id: string | null,
    in_reply_to_user_id_str: string | null,
    in_reply_to_screen_name: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string | null,
      id_str: string | null,
      name: string | null,
      screen_name: string | null,
      location: string | null,
      url: string | null,
      description: string | null,
      protected: boolean | null,
      verified: boolean | null,
      followers_count: number | null,
      friends_count: number | null,
      listed_count: number | null,
      favourites_count: number | null,
      statuses_count: number | null,
      created_at: string | null,
      profile_banner_url: string | null,
      profile_image_url_https: string | null,
      default_profile: boolean | null,
      default_profile_image: boolean | null,
      withheld_in_countries: Array< string | null > | null,
      withheld_scope: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    coordinates:  {
      __typename: "Coordinates",
      coordinates: Array< number | null > | null,
      type: string | null,
    } | null,
    place:  {
      __typename: "Place",
      id: string | null,
      url: string | null,
      place_type: string | null,
      name: string | null,
      full_name: string | null,
      country_code: string | null,
      country: string | null,
    } | null,
    quoted_status_id: string | null,
    quoted_status_id_str: string | null,
    is_quote_status: boolean | null,
    quote_count: number | null,
    reply_count: number | null,
    retweet_count: number | null,
    favorite_count: number | null,
    entities:  {
      __typename: "Entity",
      hashtags:  Array< {
        __typename: "Hashtag",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      media:  Array< {
        __typename: "Media",
        display_url: string | null,
        expanded_url: string | null,
        id: string | null,
        id_str: Array< string | null > | null,
        indices: Array< number | null > | null,
        source_user_id: string | null,
        source_user_id_str: string | null,
        media_url: string | null,
        media_url_https: string | null,
        source_status_id: string | null,
        source_status_id_str: string | null,
        type: string | null,
        url: string | null,
      } | null > | null,
      urls:  Array< {
        __typename: "Url",
        display_url: string | null,
        expanded_url: string | null,
        indices: Array< number | null > | null,
        url: string | null,
      } | null > | null,
      user_mentions:  Array< {
        __typename: "UserMention",
        id: string | null,
        id_str: string | null,
        indices: Array< number | null > | null,
        name: string | null,
        screen_name: string | null,
      } | null > | null,
      symbols:  Array< {
        __typename: "Symbol",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      polls:  Array< {
        __typename: "Poll",
        options:  Array< {
          __typename: "Option",
          position: number | null,
          text: string | null,
        } | null > | null,
        end_datetime: string | null,
        duration_minutes: string | null,
      } | null > | null,
    } | null,
    favorited: boolean | null,
    retweeted: boolean | null,
    possibly_sensitive: boolean | null,
    filter_level: string | null,
    lang: string | null,
    last: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListTweetsQueryVariables = {
  filter?: ModelTweetFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListTweetsQuery = {
  listTweets:  {
    __typename: "ModelTweetConnection",
    items:  Array< {
      __typename: "Tweet",
      id: string | null,
      created_at: string | null,
      id_str: string | null,
      text: string | null,
      source: string | null,
      truncated: boolean | null,
      in_reply_to_status_id: string | null,
      in_reply_to_status_id_str: string | null,
      in_reply_to_user_id: string | null,
      in_reply_to_user_id_str: string | null,
      in_reply_to_screen_name: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string | null,
        id_str: string | null,
        name: string | null,
        screen_name: string | null,
        location: string | null,
        url: string | null,
        description: string | null,
        protected: boolean | null,
        verified: boolean | null,
        followers_count: number | null,
        friends_count: number | null,
        listed_count: number | null,
        favourites_count: number | null,
        statuses_count: number | null,
        created_at: string | null,
        profile_banner_url: string | null,
        profile_image_url_https: string | null,
        default_profile: boolean | null,
        default_profile_image: boolean | null,
        withheld_in_countries: Array< string | null > | null,
        withheld_scope: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      coordinates:  {
        __typename: "Coordinates",
        coordinates: Array< number | null > | null,
        type: string | null,
      } | null,
      place:  {
        __typename: "Place",
        id: string | null,
        url: string | null,
        place_type: string | null,
        name: string | null,
        full_name: string | null,
        country_code: string | null,
        country: string | null,
      } | null,
      quoted_status_id: string | null,
      quoted_status_id_str: string | null,
      is_quote_status: boolean | null,
      quote_count: number | null,
      reply_count: number | null,
      retweet_count: number | null,
      favorite_count: number | null,
      entities:  {
        __typename: "Entity",
        hashtags:  Array< {
          __typename: "Hashtag",
          indices: Array< number | null > | null,
          text: string | null,
        } | null > | null,
        media:  Array< {
          __typename: "Media",
          display_url: string | null,
          expanded_url: string | null,
          id: string | null,
          id_str: Array< string | null > | null,
          indices: Array< number | null > | null,
          source_user_id: string | null,
          source_user_id_str: string | null,
          media_url: string | null,
          media_url_https: string | null,
          source_status_id: string | null,
          source_status_id_str: string | null,
          type: string | null,
          url: string | null,
        } | null > | null,
        urls:  Array< {
          __typename: "Url",
          display_url: string | null,
          expanded_url: string | null,
          indices: Array< number | null > | null,
          url: string | null,
        } | null > | null,
        user_mentions:  Array< {
          __typename: "UserMention",
          id: string | null,
          id_str: string | null,
          indices: Array< number | null > | null,
          name: string | null,
          screen_name: string | null,
        } | null > | null,
        symbols:  Array< {
          __typename: "Symbol",
          indices: Array< number | null > | null,
          text: string | null,
        } | null > | null,
        polls:  Array< {
          __typename: "Poll",
          end_datetime: string | null,
          duration_minutes: string | null,
        } | null > | null,
      } | null,
      favorited: boolean | null,
      retweeted: boolean | null,
      possibly_sensitive: boolean | null,
      filter_level: string | null,
      lang: string | null,
      last: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetUserQueryVariables = {
  id: string,
};

export type GetUserQuery = {
  getUser:  {
    __typename: "User",
    id: string | null,
    id_str: string | null,
    name: string | null,
    screen_name: string | null,
    location: string | null,
    url: string | null,
    description: string | null,
    protected: boolean | null,
    verified: boolean | null,
    followers_count: number | null,
    friends_count: number | null,
    listed_count: number | null,
    favourites_count: number | null,
    statuses_count: number | null,
    created_at: string | null,
    profile_banner_url: string | null,
    profile_image_url_https: string | null,
    default_profile: boolean | null,
    default_profile_image: boolean | null,
    withheld_in_countries: Array< string | null > | null,
    withheld_scope: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListUsersQueryVariables = {
  filter?: ModelUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListUsersQuery = {
  listUsers:  {
    __typename: "ModelUserConnection",
    items:  Array< {
      __typename: "User",
      id: string | null,
      id_str: string | null,
      name: string | null,
      screen_name: string | null,
      location: string | null,
      url: string | null,
      description: string | null,
      protected: boolean | null,
      verified: boolean | null,
      followers_count: number | null,
      friends_count: number | null,
      listed_count: number | null,
      favourites_count: number | null,
      statuses_count: number | null,
      created_at: string | null,
      profile_banner_url: string | null,
      profile_image_url_https: string | null,
      default_profile: boolean | null,
      default_profile_image: boolean | null,
      withheld_in_countries: Array< string | null > | null,
      withheld_scope: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type SearchTweetsQueryVariables = {
  filter?: SearchableTweetFilterInput | null,
  sort?: SearchableTweetSortInput | null,
  limit?: number | null,
  nextToken?: string | null,
  from?: number | null,
};

export type SearchTweetsQuery = {
  searchTweets:  {
    __typename: "SearchableTweetConnection",
    items:  Array< {
      __typename: "Tweet",
      id: string | null,
      created_at: string | null,
      id_str: string | null,
      text: string | null,
      source: string | null,
      truncated: boolean | null,
      in_reply_to_status_id: string | null,
      in_reply_to_status_id_str: string | null,
      in_reply_to_user_id: string | null,
      in_reply_to_user_id_str: string | null,
      in_reply_to_screen_name: string | null,
      userID: string,
      user:  {
        __typename: "User",
        id: string | null,
        id_str: string | null,
        name: string | null,
        screen_name: string | null,
        location: string | null,
        url: string | null,
        description: string | null,
        protected: boolean | null,
        verified: boolean | null,
        followers_count: number | null,
        friends_count: number | null,
        listed_count: number | null,
        favourites_count: number | null,
        statuses_count: number | null,
        created_at: string | null,
        profile_banner_url: string | null,
        profile_image_url_https: string | null,
        default_profile: boolean | null,
        default_profile_image: boolean | null,
        withheld_in_countries: Array< string | null > | null,
        withheld_scope: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      coordinates:  {
        __typename: "Coordinates",
        coordinates: Array< number | null > | null,
        type: string | null,
      } | null,
      place:  {
        __typename: "Place",
        id: string | null,
        url: string | null,
        place_type: string | null,
        name: string | null,
        full_name: string | null,
        country_code: string | null,
        country: string | null,
      } | null,
      quoted_status_id: string | null,
      quoted_status_id_str: string | null,
      is_quote_status: boolean | null,
      quote_count: number | null,
      reply_count: number | null,
      retweet_count: number | null,
      favorite_count: number | null,
      entities:  {
        __typename: "Entity",
        hashtags:  Array< {
          __typename: "Hashtag",
          indices: Array< number | null > | null,
          text: string | null,
        } | null > | null,
        media:  Array< {
          __typename: "Media",
          display_url: string | null,
          expanded_url: string | null,
          id: string | null,
          id_str: Array< string | null > | null,
          indices: Array< number | null > | null,
          source_user_id: string | null,
          source_user_id_str: string | null,
          media_url: string | null,
          media_url_https: string | null,
          source_status_id: string | null,
          source_status_id_str: string | null,
          type: string | null,
          url: string | null,
        } | null > | null,
        urls:  Array< {
          __typename: "Url",
          display_url: string | null,
          expanded_url: string | null,
          indices: Array< number | null > | null,
          url: string | null,
        } | null > | null,
        user_mentions:  Array< {
          __typename: "UserMention",
          id: string | null,
          id_str: string | null,
          indices: Array< number | null > | null,
          name: string | null,
          screen_name: string | null,
        } | null > | null,
        symbols:  Array< {
          __typename: "Symbol",
          indices: Array< number | null > | null,
          text: string | null,
        } | null > | null,
        polls:  Array< {
          __typename: "Poll",
          end_datetime: string | null,
          duration_minutes: string | null,
        } | null > | null,
      } | null,
      favorited: boolean | null,
      retweeted: boolean | null,
      possibly_sensitive: boolean | null,
      filter_level: string | null,
      lang: string | null,
      last: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
    total: number | null,
  } | null,
};

export type OnCreateTweetSubscription = {
  onCreateTweet:  {
    __typename: "Tweet",
    id: string | null,
    created_at: string | null,
    id_str: string | null,
    text: string | null,
    source: string | null,
    truncated: boolean | null,
    in_reply_to_status_id: string | null,
    in_reply_to_status_id_str: string | null,
    in_reply_to_user_id: string | null,
    in_reply_to_user_id_str: string | null,
    in_reply_to_screen_name: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string | null,
      id_str: string | null,
      name: string | null,
      screen_name: string | null,
      location: string | null,
      url: string | null,
      description: string | null,
      protected: boolean | null,
      verified: boolean | null,
      followers_count: number | null,
      friends_count: number | null,
      listed_count: number | null,
      favourites_count: number | null,
      statuses_count: number | null,
      created_at: string | null,
      profile_banner_url: string | null,
      profile_image_url_https: string | null,
      default_profile: boolean | null,
      default_profile_image: boolean | null,
      withheld_in_countries: Array< string | null > | null,
      withheld_scope: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    coordinates:  {
      __typename: "Coordinates",
      coordinates: Array< number | null > | null,
      type: string | null,
    } | null,
    place:  {
      __typename: "Place",
      id: string | null,
      url: string | null,
      place_type: string | null,
      name: string | null,
      full_name: string | null,
      country_code: string | null,
      country: string | null,
    } | null,
    quoted_status_id: string | null,
    quoted_status_id_str: string | null,
    is_quote_status: boolean | null,
    quote_count: number | null,
    reply_count: number | null,
    retweet_count: number | null,
    favorite_count: number | null,
    entities:  {
      __typename: "Entity",
      hashtags:  Array< {
        __typename: "Hashtag",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      media:  Array< {
        __typename: "Media",
        display_url: string | null,
        expanded_url: string | null,
        id: string | null,
        id_str: Array< string | null > | null,
        indices: Array< number | null > | null,
        source_user_id: string | null,
        source_user_id_str: string | null,
        media_url: string | null,
        media_url_https: string | null,
        source_status_id: string | null,
        source_status_id_str: string | null,
        type: string | null,
        url: string | null,
      } | null > | null,
      urls:  Array< {
        __typename: "Url",
        display_url: string | null,
        expanded_url: string | null,
        indices: Array< number | null > | null,
        url: string | null,
      } | null > | null,
      user_mentions:  Array< {
        __typename: "UserMention",
        id: string | null,
        id_str: string | null,
        indices: Array< number | null > | null,
        name: string | null,
        screen_name: string | null,
      } | null > | null,
      symbols:  Array< {
        __typename: "Symbol",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      polls:  Array< {
        __typename: "Poll",
        options:  Array< {
          __typename: "Option",
          position: number | null,
          text: string | null,
        } | null > | null,
        end_datetime: string | null,
        duration_minutes: string | null,
      } | null > | null,
    } | null,
    favorited: boolean | null,
    retweeted: boolean | null,
    possibly_sensitive: boolean | null,
    filter_level: string | null,
    lang: string | null,
    last: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateTweetSubscription = {
  onUpdateTweet:  {
    __typename: "Tweet",
    id: string | null,
    created_at: string | null,
    id_str: string | null,
    text: string | null,
    source: string | null,
    truncated: boolean | null,
    in_reply_to_status_id: string | null,
    in_reply_to_status_id_str: string | null,
    in_reply_to_user_id: string | null,
    in_reply_to_user_id_str: string | null,
    in_reply_to_screen_name: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string | null,
      id_str: string | null,
      name: string | null,
      screen_name: string | null,
      location: string | null,
      url: string | null,
      description: string | null,
      protected: boolean | null,
      verified: boolean | null,
      followers_count: number | null,
      friends_count: number | null,
      listed_count: number | null,
      favourites_count: number | null,
      statuses_count: number | null,
      created_at: string | null,
      profile_banner_url: string | null,
      profile_image_url_https: string | null,
      default_profile: boolean | null,
      default_profile_image: boolean | null,
      withheld_in_countries: Array< string | null > | null,
      withheld_scope: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    coordinates:  {
      __typename: "Coordinates",
      coordinates: Array< number | null > | null,
      type: string | null,
    } | null,
    place:  {
      __typename: "Place",
      id: string | null,
      url: string | null,
      place_type: string | null,
      name: string | null,
      full_name: string | null,
      country_code: string | null,
      country: string | null,
    } | null,
    quoted_status_id: string | null,
    quoted_status_id_str: string | null,
    is_quote_status: boolean | null,
    quote_count: number | null,
    reply_count: number | null,
    retweet_count: number | null,
    favorite_count: number | null,
    entities:  {
      __typename: "Entity",
      hashtags:  Array< {
        __typename: "Hashtag",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      media:  Array< {
        __typename: "Media",
        display_url: string | null,
        expanded_url: string | null,
        id: string | null,
        id_str: Array< string | null > | null,
        indices: Array< number | null > | null,
        source_user_id: string | null,
        source_user_id_str: string | null,
        media_url: string | null,
        media_url_https: string | null,
        source_status_id: string | null,
        source_status_id_str: string | null,
        type: string | null,
        url: string | null,
      } | null > | null,
      urls:  Array< {
        __typename: "Url",
        display_url: string | null,
        expanded_url: string | null,
        indices: Array< number | null > | null,
        url: string | null,
      } | null > | null,
      user_mentions:  Array< {
        __typename: "UserMention",
        id: string | null,
        id_str: string | null,
        indices: Array< number | null > | null,
        name: string | null,
        screen_name: string | null,
      } | null > | null,
      symbols:  Array< {
        __typename: "Symbol",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      polls:  Array< {
        __typename: "Poll",
        options:  Array< {
          __typename: "Option",
          position: number | null,
          text: string | null,
        } | null > | null,
        end_datetime: string | null,
        duration_minutes: string | null,
      } | null > | null,
    } | null,
    favorited: boolean | null,
    retweeted: boolean | null,
    possibly_sensitive: boolean | null,
    filter_level: string | null,
    lang: string | null,
    last: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteTweetSubscription = {
  onDeleteTweet:  {
    __typename: "Tweet",
    id: string | null,
    created_at: string | null,
    id_str: string | null,
    text: string | null,
    source: string | null,
    truncated: boolean | null,
    in_reply_to_status_id: string | null,
    in_reply_to_status_id_str: string | null,
    in_reply_to_user_id: string | null,
    in_reply_to_user_id_str: string | null,
    in_reply_to_screen_name: string | null,
    userID: string,
    user:  {
      __typename: "User",
      id: string | null,
      id_str: string | null,
      name: string | null,
      screen_name: string | null,
      location: string | null,
      url: string | null,
      description: string | null,
      protected: boolean | null,
      verified: boolean | null,
      followers_count: number | null,
      friends_count: number | null,
      listed_count: number | null,
      favourites_count: number | null,
      statuses_count: number | null,
      created_at: string | null,
      profile_banner_url: string | null,
      profile_image_url_https: string | null,
      default_profile: boolean | null,
      default_profile_image: boolean | null,
      withheld_in_countries: Array< string | null > | null,
      withheld_scope: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    coordinates:  {
      __typename: "Coordinates",
      coordinates: Array< number | null > | null,
      type: string | null,
    } | null,
    place:  {
      __typename: "Place",
      id: string | null,
      url: string | null,
      place_type: string | null,
      name: string | null,
      full_name: string | null,
      country_code: string | null,
      country: string | null,
    } | null,
    quoted_status_id: string | null,
    quoted_status_id_str: string | null,
    is_quote_status: boolean | null,
    quote_count: number | null,
    reply_count: number | null,
    retweet_count: number | null,
    favorite_count: number | null,
    entities:  {
      __typename: "Entity",
      hashtags:  Array< {
        __typename: "Hashtag",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      media:  Array< {
        __typename: "Media",
        display_url: string | null,
        expanded_url: string | null,
        id: string | null,
        id_str: Array< string | null > | null,
        indices: Array< number | null > | null,
        source_user_id: string | null,
        source_user_id_str: string | null,
        media_url: string | null,
        media_url_https: string | null,
        source_status_id: string | null,
        source_status_id_str: string | null,
        type: string | null,
        url: string | null,
      } | null > | null,
      urls:  Array< {
        __typename: "Url",
        display_url: string | null,
        expanded_url: string | null,
        indices: Array< number | null > | null,
        url: string | null,
      } | null > | null,
      user_mentions:  Array< {
        __typename: "UserMention",
        id: string | null,
        id_str: string | null,
        indices: Array< number | null > | null,
        name: string | null,
        screen_name: string | null,
      } | null > | null,
      symbols:  Array< {
        __typename: "Symbol",
        indices: Array< number | null > | null,
        text: string | null,
      } | null > | null,
      polls:  Array< {
        __typename: "Poll",
        options:  Array< {
          __typename: "Option",
          position: number | null,
          text: string | null,
        } | null > | null,
        end_datetime: string | null,
        duration_minutes: string | null,
      } | null > | null,
    } | null,
    favorited: boolean | null,
    retweeted: boolean | null,
    possibly_sensitive: boolean | null,
    filter_level: string | null,
    lang: string | null,
    last: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateUserSubscription = {
  onCreateUser:  {
    __typename: "User",
    id: string | null,
    id_str: string | null,
    name: string | null,
    screen_name: string | null,
    location: string | null,
    url: string | null,
    description: string | null,
    protected: boolean | null,
    verified: boolean | null,
    followers_count: number | null,
    friends_count: number | null,
    listed_count: number | null,
    favourites_count: number | null,
    statuses_count: number | null,
    created_at: string | null,
    profile_banner_url: string | null,
    profile_image_url_https: string | null,
    default_profile: boolean | null,
    default_profile_image: boolean | null,
    withheld_in_countries: Array< string | null > | null,
    withheld_scope: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateUserSubscription = {
  onUpdateUser:  {
    __typename: "User",
    id: string | null,
    id_str: string | null,
    name: string | null,
    screen_name: string | null,
    location: string | null,
    url: string | null,
    description: string | null,
    protected: boolean | null,
    verified: boolean | null,
    followers_count: number | null,
    friends_count: number | null,
    listed_count: number | null,
    favourites_count: number | null,
    statuses_count: number | null,
    created_at: string | null,
    profile_banner_url: string | null,
    profile_image_url_https: string | null,
    default_profile: boolean | null,
    default_profile_image: boolean | null,
    withheld_in_countries: Array< string | null > | null,
    withheld_scope: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteUserSubscription = {
  onDeleteUser:  {
    __typename: "User",
    id: string | null,
    id_str: string | null,
    name: string | null,
    screen_name: string | null,
    location: string | null,
    url: string | null,
    description: string | null,
    protected: boolean | null,
    verified: boolean | null,
    followers_count: number | null,
    friends_count: number | null,
    listed_count: number | null,
    favourites_count: number | null,
    statuses_count: number | null,
    created_at: string | null,
    profile_banner_url: string | null,
    profile_image_url_https: string | null,
    default_profile: boolean | null,
    default_profile_image: boolean | null,
    withheld_in_countries: Array< string | null > | null,
    withheld_scope: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
